name: Build Docker image

on:
  pull_request:

jobs:
  docker:
    name: Build Docker image
    env:
      IMAGE_NAME: monotek/patron-selfheal
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
