name: Push to Registry

on:
  push:
    branches:
      - 'main'
      - 'dev'
    tags:
      - '*'

jobs:
  docker:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    name: Push Docker Image
    env:
      IMAGE_NAME: monotek/patroni-selfheal
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (dev)
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${IMAGE_NAME}:dev-${GITHUB_SHA::8}

      - name: Build (master)
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${IMAGE_NAME}:master-${GITHUB_SHA::8},${IMAGE_NAME}:latest

      - name: Build (git tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${IMAGE_NAME}:${GITHUB_REF:10},${IMAGE_NAME}:${DOCKER_TAG}
